server.port=8089

orden.service.url=${ORDER_MS_URL}
products.service.url=http://java_app_products_ms:8082/api/products

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
